2022-03-01 04:13:15,837 INFO    MainThread:3232 [internal.py:wandb_internal():90] W&B internal server running at pid: 3232, started at: 2022-03-01 04:13:15.835266
2022-03-01 04:13:15,853 INFO    WriterThread:3232 [datastore.py:open_for_write():77] open: /home/ersp2021/FedML-Server-XF/executor/wandb/offline-run-20220301_041310-3ut9xypj/run-3ut9xypj.wandb
2022-03-01 04:13:15,866 DEBUG   HandlerThread:3232 [handler.py:handle_request():130] handle_request: run_start
2022-03-01 04:13:15,873 DEBUG   HandlerThread:3232 [meta.py:__init__():40] meta init
2022-03-01 04:13:15,873 DEBUG   HandlerThread:3232 [meta.py:__init__():54] meta init done
2022-03-01 04:13:15,874 DEBUG   HandlerThread:3232 [meta.py:probe():214] probe
2022-03-01 04:13:15,887 DEBUG   HandlerThread:3232 [meta.py:_setup_git():204] setup git
2022-03-01 04:13:15,973 DEBUG   HandlerThread:3232 [meta.py:_setup_git():211] setup git done
2022-03-01 04:13:15,974 DEBUG   HandlerThread:3232 [meta.py:_save_pip():58] save pip
2022-03-01 04:13:15,976 DEBUG   HandlerThread:3232 [meta.py:_save_pip():72] save pip done
2022-03-01 04:13:15,977 DEBUG   HandlerThread:3232 [meta.py:_save_conda():79] save conda
2022-03-01 04:13:35,455 DEBUG   HandlerThread:3232 [meta.py:_save_conda():89] save conda done
2022-03-01 04:13:35,457 DEBUG   HandlerThread:3232 [meta.py:probe():252] probe done
2022-03-01 04:20:39,566 WARNING MainThread:3232 [internal.py:wandb_internal():146] Internal process interrupt: 1
2022-03-01 04:20:41,287 WARNING MainThread:3232 [internal.py:wandb_internal():146] Internal process interrupt: 2
2022-03-01 04:20:41,288 ERROR   MainThread:3232 [internal.py:wandb_internal():149] Internal process interrupted.
2022-03-01 04:20:41,629 INFO    SenderThread:3232 [sender.py:finish():1070] shutting down sender
2022-03-01 04:20:42,114 INFO    WriterThread:3232 [datastore.py:close():281] close: /home/ersp2021/FedML-Server-XF/executor/wandb/offline-run-20220301_041310-3ut9xypj/run-3ut9xypj.wandb
2022-03-01 04:20:42,115 INFO    HandlerThread:3232 [handler.py:finish():731] shutting down handler
2022-03-01 04:20:42,117 INFO    MainThread:3232 [internal.py:handle_exit():77] Internal process exited
