2022-02-14 10:06:59,609 INFO    MainThread:18387 [internal.py:wandb_internal():92] W&B internal server running at pid: 18387, started at: 2022-02-14 10:06:59.608972
2022-02-14 10:06:59,618 DEBUG   HandlerThread:18387 [handler.py:handle_request():131] handle_request: run_start
2022-02-14 10:06:59,618 INFO    WriterThread:18387 [datastore.py:open_for_write():77] open: /home/pi/FedML-Server/executor/wandb/offline-run-20220214_100658-12mocuii/run-12mocuii.wandb
2022-02-14 10:06:59,624 DEBUG   HandlerThread:18387 [meta.py:__init__():36] meta init
2022-02-14 10:06:59,624 DEBUG   HandlerThread:18387 [meta.py:__init__():50] meta init done
2022-02-14 10:06:59,625 DEBUG   HandlerThread:18387 [meta.py:probe():210] probe
2022-02-14 10:06:59,628 DEBUG   HandlerThread:18387 [meta.py:_setup_git():200] setup git
2022-02-14 10:06:59,657 DEBUG   HandlerThread:18387 [meta.py:_setup_git():207] setup git done
2022-02-14 10:06:59,657 DEBUG   HandlerThread:18387 [meta.py:_save_pip():54] save pip
2022-02-14 10:06:59,658 DEBUG   HandlerThread:18387 [meta.py:_save_pip():68] save pip done
2022-02-14 10:06:59,659 DEBUG   HandlerThread:18387 [meta.py:probe():248] probe done
2022-02-14 10:40:43,628 WARNING MainThread:18387 [internal.py:wandb_internal():152] Internal process interrupt: 1
2022-02-14 10:40:44,981 WARNING MainThread:18387 [internal.py:wandb_internal():152] Internal process interrupt: 2
2022-02-14 10:40:44,981 ERROR   MainThread:18387 [internal.py:wandb_internal():155] Internal process interrupted.
2022-02-14 10:40:45,172 INFO    SenderThread:18387 [sender.py:finish():1075] shutting down sender
2022-02-14 10:40:45,438 INFO    WriterThread:18387 [datastore.py:close():281] close: /home/pi/FedML-Server/executor/wandb/offline-run-20220214_100658-12mocuii/run-12mocuii.wandb
2022-02-14 10:40:45,447 INFO    HandlerThread:18387 [handler.py:finish():739] shutting down handler
2022-02-14 10:40:45,448 INFO    MainThread:18387 [internal.py:handle_exit():79] Internal process exited
