2022-02-14 06:10:27,059 INFO    MainThread:7388 [internal.py:wandb_internal():92] W&B internal server running at pid: 7388, started at: 2022-02-14 06:10:27.058329
2022-02-14 06:10:27,067 DEBUG   HandlerThread:7388 [handler.py:handle_request():131] handle_request: run_start
2022-02-14 06:10:27,067 INFO    WriterThread:7388 [datastore.py:open_for_write():77] open: /home/pi/FedML-Server/executor/wandb/offline-run-20220214_061025-2knng4av/run-2knng4av.wandb
2022-02-14 06:10:27,073 DEBUG   HandlerThread:7388 [meta.py:__init__():36] meta init
2022-02-14 06:10:27,074 DEBUG   HandlerThread:7388 [meta.py:__init__():50] meta init done
2022-02-14 06:10:27,074 DEBUG   HandlerThread:7388 [meta.py:probe():210] probe
2022-02-14 06:10:27,077 DEBUG   HandlerThread:7388 [meta.py:_setup_git():200] setup git
2022-02-14 06:10:27,106 DEBUG   HandlerThread:7388 [meta.py:_setup_git():207] setup git done
2022-02-14 06:10:27,107 DEBUG   HandlerThread:7388 [meta.py:_save_pip():54] save pip
2022-02-14 06:10:27,108 DEBUG   HandlerThread:7388 [meta.py:_save_pip():68] save pip done
2022-02-14 06:10:27,108 DEBUG   HandlerThread:7388 [meta.py:probe():248] probe done
2022-02-14 06:22:54,158 WARNING MainThread:7388 [internal.py:wandb_internal():152] Internal process interrupt: 1
2022-02-14 06:22:54,858 WARNING MainThread:7388 [internal.py:wandb_internal():152] Internal process interrupt: 2
2022-02-14 06:22:54,859 ERROR   MainThread:7388 [internal.py:wandb_internal():155] Internal process interrupted.
2022-02-14 06:22:55,014 INFO    WriterThread:7388 [datastore.py:close():281] close: /home/pi/FedML-Server/executor/wandb/offline-run-20220214_061025-2knng4av/run-2knng4av.wandb
2022-02-14 06:22:55,042 INFO    HandlerThread:7388 [handler.py:finish():739] shutting down handler
2022-02-14 06:22:55,287 INFO    SenderThread:7388 [sender.py:finish():1075] shutting down sender
2022-02-14 06:22:55,289 INFO    MainThread:7388 [internal.py:handle_exit():79] Internal process exited
