2022-03-01 05:17:42,181 INFO    MainThread:4108 [internal.py:wandb_internal():90] W&B internal server running at pid: 4108, started at: 2022-03-01 05:17:42.179097
2022-03-01 05:17:42,203 DEBUG   HandlerThread:4108 [handler.py:handle_request():130] handle_request: run_start
2022-03-01 05:17:42,205 INFO    WriterThread:4108 [datastore.py:open_for_write():77] open: /home/ersp2021/FedML-Server-XF/executor/wandb/offline-run-20220301_051737-2mqtp7lx/run-2mqtp7lx.wandb
2022-03-01 05:17:42,213 DEBUG   HandlerThread:4108 [meta.py:__init__():40] meta init
2022-03-01 05:17:42,214 DEBUG   HandlerThread:4108 [meta.py:__init__():54] meta init done
2022-03-01 05:17:42,214 DEBUG   HandlerThread:4108 [meta.py:probe():214] probe
2022-03-01 05:17:42,224 DEBUG   HandlerThread:4108 [meta.py:_setup_git():204] setup git
2022-03-01 05:17:42,297 DEBUG   HandlerThread:4108 [meta.py:_setup_git():211] setup git done
2022-03-01 05:17:42,298 DEBUG   HandlerThread:4108 [meta.py:_save_pip():58] save pip
2022-03-01 05:17:42,301 DEBUG   HandlerThread:4108 [meta.py:_save_pip():72] save pip done
2022-03-01 05:17:42,301 DEBUG   HandlerThread:4108 [meta.py:_save_conda():79] save conda
2022-03-01 05:17:57,950 DEBUG   HandlerThread:4108 [meta.py:_save_conda():89] save conda done
2022-03-01 05:17:57,951 DEBUG   HandlerThread:4108 [meta.py:probe():252] probe done
2022-03-01 05:19:04,334 WARNING MainThread:4108 [internal.py:wandb_internal():146] Internal process interrupt: 1
2022-03-01 05:19:04,510 WARNING MainThread:4108 [internal.py:wandb_internal():146] Internal process interrupt: 2
2022-03-01 05:19:04,511 ERROR   MainThread:4108 [internal.py:wandb_internal():149] Internal process interrupted.
2022-03-01 05:19:04,568 INFO    SenderThread:4108 [sender.py:finish():1070] shutting down sender
2022-03-01 05:19:04,693 INFO    WriterThread:4108 [datastore.py:close():281] close: /home/ersp2021/FedML-Server-XF/executor/wandb/offline-run-20220301_051737-2mqtp7lx/run-2mqtp7lx.wandb
2022-03-01 05:19:04,696 INFO    HandlerThread:4108 [handler.py:finish():731] shutting down handler
2022-03-01 05:19:04,699 INFO    MainThread:4108 [internal.py:handle_exit():77] Internal process exited
