2022-02-14 18:32:53,129 INFO    MainThread:15713 [internal.py:wandb_internal():92] W&B internal server running at pid: 15713, started at: 2022-02-14 18:32:53.128995
2022-02-14 18:32:53,138 DEBUG   HandlerThread:15713 [handler.py:handle_request():131] handle_request: run_start
2022-02-14 18:32:53,139 INFO    WriterThread:15713 [datastore.py:open_for_write():77] open: /home/pi/FedML-Server/executor/wandb/offline-run-20220214_183251-220wld3j/run-220wld3j.wandb
2022-02-14 18:32:53,144 DEBUG   HandlerThread:15713 [meta.py:__init__():36] meta init
2022-02-14 18:32:53,144 DEBUG   HandlerThread:15713 [meta.py:__init__():50] meta init done
2022-02-14 18:32:53,145 DEBUG   HandlerThread:15713 [meta.py:probe():210] probe
2022-02-14 18:32:53,148 DEBUG   HandlerThread:15713 [meta.py:_setup_git():200] setup git
2022-02-14 18:32:53,177 DEBUG   HandlerThread:15713 [meta.py:_setup_git():207] setup git done
2022-02-14 18:32:53,178 DEBUG   HandlerThread:15713 [meta.py:_save_pip():54] save pip
2022-02-14 18:32:53,179 DEBUG   HandlerThread:15713 [meta.py:_save_pip():68] save pip done
2022-02-14 18:32:53,179 DEBUG   HandlerThread:15713 [meta.py:probe():248] probe done
2022-02-14 18:46:16,449 WARNING MainThread:15713 [internal.py:wandb_internal():152] Internal process interrupt: 1
2022-02-14 18:46:16,757 WARNING MainThread:15713 [internal.py:wandb_internal():152] Internal process interrupt: 2
2022-02-14 18:46:16,757 ERROR   MainThread:15713 [internal.py:wandb_internal():155] Internal process interrupted.
2022-02-14 18:46:17,241 INFO    WriterThread:15713 [datastore.py:close():281] close: /home/pi/FedML-Server/executor/wandb/offline-run-20220214_183251-220wld3j/run-220wld3j.wandb
2022-02-14 18:46:17,263 INFO    HandlerThread:15713 [handler.py:finish():739] shutting down handler
2022-02-14 18:46:17,355 INFO    SenderThread:15713 [sender.py:finish():1075] shutting down sender
2022-02-14 18:46:17,356 INFO    MainThread:15713 [internal.py:handle_exit():79] Internal process exited
