2022-02-14 07:19:19,415 INFO    MainThread:14155 [internal.py:wandb_internal():92] W&B internal server running at pid: 14155, started at: 2022-02-14 07:19:19.414818
2022-02-14 07:19:19,424 DEBUG   HandlerThread:14155 [handler.py:handle_request():131] handle_request: run_start
2022-02-14 07:19:19,424 INFO    WriterThread:14155 [datastore.py:open_for_write():77] open: /home/pi/FedML-Server/executor/wandb/offline-run-20220214_071917-eomfub7f/run-eomfub7f.wandb
2022-02-14 07:19:19,430 DEBUG   HandlerThread:14155 [meta.py:__init__():36] meta init
2022-02-14 07:19:19,430 DEBUG   HandlerThread:14155 [meta.py:__init__():50] meta init done
2022-02-14 07:19:19,431 DEBUG   HandlerThread:14155 [meta.py:probe():210] probe
2022-02-14 07:19:19,433 DEBUG   HandlerThread:14155 [meta.py:_setup_git():200] setup git
2022-02-14 07:19:19,463 DEBUG   HandlerThread:14155 [meta.py:_setup_git():207] setup git done
2022-02-14 07:19:19,463 DEBUG   HandlerThread:14155 [meta.py:_save_pip():54] save pip
2022-02-14 07:19:19,464 DEBUG   HandlerThread:14155 [meta.py:_save_pip():68] save pip done
2022-02-14 07:19:19,465 DEBUG   HandlerThread:14155 [meta.py:probe():248] probe done
2022-02-14 07:55:07,516 WARNING MainThread:14155 [internal.py:wandb_internal():152] Internal process interrupt: 1
2022-02-14 07:55:09,338 WARNING MainThread:14155 [internal.py:wandb_internal():152] Internal process interrupt: 2
2022-02-14 07:55:09,339 ERROR   MainThread:14155 [internal.py:wandb_internal():155] Internal process interrupted.
2022-02-14 07:55:09,709 INFO    WriterThread:14155 [datastore.py:close():281] close: /home/pi/FedML-Server/executor/wandb/offline-run-20220214_071917-eomfub7f/run-eomfub7f.wandb
2022-02-14 07:55:09,710 INFO    HandlerThread:14155 [handler.py:finish():739] shutting down handler
2022-02-14 07:55:09,909 INFO    SenderThread:14155 [sender.py:finish():1075] shutting down sender
2022-02-14 07:55:09,910 INFO    MainThread:14155 [internal.py:handle_exit():79] Internal process exited
