2022-02-14 17:47:01,933 INFO    MainThread:11882 [internal.py:wandb_internal():92] W&B internal server running at pid: 11882, started at: 2022-02-14 17:47:01.932496
2022-02-14 17:47:01,941 DEBUG   HandlerThread:11882 [handler.py:handle_request():131] handle_request: run_start
2022-02-14 17:47:01,942 INFO    WriterThread:11882 [datastore.py:open_for_write():77] open: /home/pi/FedML-Server/executor/wandb/offline-run-20220214_174700-19o1jtbr/run-19o1jtbr.wandb
2022-02-14 17:47:01,948 DEBUG   HandlerThread:11882 [meta.py:__init__():36] meta init
2022-02-14 17:47:01,948 DEBUG   HandlerThread:11882 [meta.py:__init__():50] meta init done
2022-02-14 17:47:01,948 DEBUG   HandlerThread:11882 [meta.py:probe():210] probe
2022-02-14 17:47:01,951 DEBUG   HandlerThread:11882 [meta.py:_setup_git():200] setup git
2022-02-14 17:47:01,980 DEBUG   HandlerThread:11882 [meta.py:_setup_git():207] setup git done
2022-02-14 17:47:01,981 DEBUG   HandlerThread:11882 [meta.py:_save_pip():54] save pip
2022-02-14 17:47:01,982 DEBUG   HandlerThread:11882 [meta.py:_save_pip():68] save pip done
2022-02-14 17:47:01,982 DEBUG   HandlerThread:11882 [meta.py:probe():248] probe done
2022-02-14 18:02:11,731 WARNING MainThread:11882 [internal.py:wandb_internal():152] Internal process interrupt: 1
2022-02-14 18:02:12,194 WARNING MainThread:11882 [internal.py:wandb_internal():152] Internal process interrupt: 2
2022-02-14 18:02:12,195 ERROR   MainThread:11882 [internal.py:wandb_internal():155] Internal process interrupted.
2022-02-14 18:02:12,304 INFO    WriterThread:11882 [datastore.py:close():281] close: /home/pi/FedML-Server/executor/wandb/offline-run-20220214_174700-19o1jtbr/run-19o1jtbr.wandb
2022-02-14 18:02:12,314 INFO    HandlerThread:11882 [handler.py:finish():739] shutting down handler
2022-02-14 18:02:13,140 INFO    SenderThread:11882 [sender.py:finish():1075] shutting down sender
2022-02-14 18:02:13,143 INFO    MainThread:11882 [internal.py:handle_exit():79] Internal process exited
