2022-02-14 21:36:25,667 INFO    MainThread:6098 [internal.py:wandb_internal():92] W&B internal server running at pid: 6098, started at: 2022-02-14 21:36:25.666749
2022-02-14 21:36:25,675 DEBUG   HandlerThread:6098 [handler.py:handle_request():131] handle_request: run_start
2022-02-14 21:36:25,676 INFO    WriterThread:6098 [datastore.py:open_for_write():77] open: /home/pi/FedML-Server/executor/wandb/offline-run-20220214_213624-25tu0a80/run-25tu0a80.wandb
2022-02-14 21:36:25,682 DEBUG   HandlerThread:6098 [meta.py:__init__():36] meta init
2022-02-14 21:36:25,682 DEBUG   HandlerThread:6098 [meta.py:__init__():50] meta init done
2022-02-14 21:36:25,682 DEBUG   HandlerThread:6098 [meta.py:probe():210] probe
2022-02-14 21:36:25,685 DEBUG   HandlerThread:6098 [meta.py:_setup_git():200] setup git
2022-02-14 21:36:25,715 DEBUG   HandlerThread:6098 [meta.py:_setup_git():207] setup git done
2022-02-14 21:36:25,715 DEBUG   HandlerThread:6098 [meta.py:_save_pip():54] save pip
2022-02-14 21:36:25,717 DEBUG   HandlerThread:6098 [meta.py:_save_pip():68] save pip done
2022-02-14 21:36:25,717 DEBUG   HandlerThread:6098 [meta.py:probe():248] probe done
2022-02-14 21:52:05,334 WARNING MainThread:6098 [internal.py:wandb_internal():152] Internal process interrupt: 1
2022-02-14 21:52:06,180 WARNING MainThread:6098 [internal.py:wandb_internal():152] Internal process interrupt: 2
2022-02-14 21:52:06,181 ERROR   MainThread:6098 [internal.py:wandb_internal():155] Internal process interrupted.
2022-02-14 21:52:06,895 INFO    SenderThread:6098 [sender.py:finish():1075] shutting down sender
2022-02-14 21:52:07,035 INFO    WriterThread:6098 [datastore.py:close():281] close: /home/pi/FedML-Server/executor/wandb/offline-run-20220214_213624-25tu0a80/run-25tu0a80.wandb
2022-02-14 21:52:07,044 INFO    HandlerThread:6098 [handler.py:finish():739] shutting down handler
2022-02-14 21:52:07,047 INFO    MainThread:6098 [internal.py:handle_exit():79] Internal process exited
