2022-02-14 00:05:41,587 INFO    MainThread:23053 [internal.py:wandb_internal():92] W&B internal server running at pid: 23053, started at: 2022-02-14 00:05:41.586566
2022-02-14 00:05:41,595 DEBUG   HandlerThread:23053 [handler.py:handle_request():131] handle_request: run_start
2022-02-14 00:05:41,596 INFO    WriterThread:23053 [datastore.py:open_for_write():77] open: /home/pi/FedML-Server/executor/wandb/offline-run-20220214_000539-18d6bzs0/run-18d6bzs0.wandb
2022-02-14 00:05:41,602 DEBUG   HandlerThread:23053 [meta.py:__init__():36] meta init
2022-02-14 00:05:41,602 DEBUG   HandlerThread:23053 [meta.py:__init__():50] meta init done
2022-02-14 00:05:41,602 DEBUG   HandlerThread:23053 [meta.py:probe():210] probe
2022-02-14 00:05:41,605 DEBUG   HandlerThread:23053 [meta.py:_setup_git():200] setup git
2022-02-14 00:05:41,635 DEBUG   HandlerThread:23053 [meta.py:_setup_git():207] setup git done
2022-02-14 00:05:41,636 DEBUG   HandlerThread:23053 [meta.py:_save_pip():54] save pip
2022-02-14 00:05:41,637 DEBUG   HandlerThread:23053 [meta.py:_save_pip():68] save pip done
2022-02-14 00:05:41,637 DEBUG   HandlerThread:23053 [meta.py:probe():248] probe done
2022-02-14 00:08:35,216 WARNING MainThread:23053 [internal.py:wandb_internal():152] Internal process interrupt: 1
2022-02-14 00:08:35,681 WARNING MainThread:23053 [internal.py:wandb_internal():152] Internal process interrupt: 2
2022-02-14 00:08:35,682 ERROR   MainThread:23053 [internal.py:wandb_internal():155] Internal process interrupted.
2022-02-14 00:08:36,139 INFO    WriterThread:23053 [datastore.py:close():281] close: /home/pi/FedML-Server/executor/wandb/offline-run-20220214_000539-18d6bzs0/run-18d6bzs0.wandb
2022-02-14 00:08:36,165 INFO    HandlerThread:23053 [handler.py:finish():739] shutting down handler
2022-02-14 00:08:36,639 INFO    SenderThread:23053 [sender.py:finish():1075] shutting down sender
2022-02-14 00:08:36,641 INFO    MainThread:23053 [internal.py:handle_exit():79] Internal process exited
