2022-02-14 19:15:54,397 INFO    MainThread:16473 [internal.py:wandb_internal():92] W&B internal server running at pid: 16473, started at: 2022-02-14 19:15:54.396696
2022-02-14 19:15:54,405 DEBUG   HandlerThread:16473 [handler.py:handle_request():131] handle_request: run_start
2022-02-14 19:15:54,406 INFO    WriterThread:16473 [datastore.py:open_for_write():77] open: /home/pi/FedML-Server/executor/wandb/offline-run-20220214_191552-2nrfav8a/run-2nrfav8a.wandb
2022-02-14 19:15:54,412 DEBUG   HandlerThread:16473 [meta.py:__init__():36] meta init
2022-02-14 19:15:54,412 DEBUG   HandlerThread:16473 [meta.py:__init__():50] meta init done
2022-02-14 19:15:54,412 DEBUG   HandlerThread:16473 [meta.py:probe():210] probe
2022-02-14 19:15:54,415 DEBUG   HandlerThread:16473 [meta.py:_setup_git():200] setup git
2022-02-14 19:15:54,445 DEBUG   HandlerThread:16473 [meta.py:_setup_git():207] setup git done
2022-02-14 19:15:54,446 DEBUG   HandlerThread:16473 [meta.py:_save_pip():54] save pip
2022-02-14 19:15:54,447 DEBUG   HandlerThread:16473 [meta.py:_save_pip():68] save pip done
2022-02-14 19:15:54,447 DEBUG   HandlerThread:16473 [meta.py:probe():248] probe done
2022-02-14 19:32:45,452 WARNING MainThread:16473 [internal.py:wandb_internal():152] Internal process interrupt: 1
2022-02-14 19:32:45,878 WARNING MainThread:16473 [internal.py:wandb_internal():152] Internal process interrupt: 2
2022-02-14 19:32:45,879 ERROR   MainThread:16473 [internal.py:wandb_internal():155] Internal process interrupted.
2022-02-14 19:32:46,197 INFO    WriterThread:16473 [datastore.py:close():281] close: /home/pi/FedML-Server/executor/wandb/offline-run-20220214_191552-2nrfav8a/run-2nrfav8a.wandb
2022-02-14 19:32:46,217 INFO    HandlerThread:16473 [handler.py:finish():739] shutting down handler
2022-02-14 19:32:46,692 INFO    SenderThread:16473 [sender.py:finish():1075] shutting down sender
2022-02-14 19:32:46,695 INFO    MainThread:16473 [internal.py:handle_exit():79] Internal process exited
